### PR TITLE
Fix http staffs

### PR DESCRIPTION
**Pull request by MugeSo**
- Fix http.json in local is tried to read via http access
- Enhance to use only before fragment identifier as cache key

### CODE REVIEW

**Comment by MugeSo** [comment]
Sorry to say, i can not run test in my environmet(windows 10 + node 5.6.0) since before this change.

I got:

```
SyntaxError: Unexpected token .
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:387:25)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (C:\Users\Koichi\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (D:\Users\Koichi\Documents\OSS\json-ref-lite\test\test.coffee:1:8)
  at Object.<anonymous> (D:\Users\Koichi\Documents\OSS\json-ref-lite\test\test.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.exports.run (C:\Users\Koichi\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:134:23)
  at compileScript (C:\Users\Koichi\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
  at compilePath (C:\Users\Koichi\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
  at Object.exports.run (C:\Users\Koichi\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
  at Object.<anonymous> (C:\Users\Koichi\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee:7:41)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:140:18)
  at node.js:1001:3

```

So, I did test this change too.

**Comment by MugeSo** [comment]
Test is passed in e8002ad

**Comment by coderofsalvation** [comment]
MugeSo: thx for your PR, all make sense however:

```
-        else if request and String(ref).match /^http/
+        else if request and String(ref).match /^https?:/
```

Not sure if I get this, but why would you only want to match https-urls?
The current version allows both http and https..

Let me know and I'll merge it.

**Comment by MugeSo** [comment]
`/^https?:/` matches both of `http:` and `https:`.
`?` means previous character is optional.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-questionmark

**Comment by coderofsalvation** [comment]
agreed, however '^http' also matches both 'https' and 'http'.
Aaaaanyways, the regex doesn't hurt and the windowsfix is great, so thanks.
Its merged now.

**Pull request merged**
